alias: Chores - Reset Monthly Toggle
description: Reset Monthly Chores
triggers: []
conditions:
  - condition: template
    value_template: "{{ now().day == 1 }}"
actions:
  - target:
      entity_id:
        - input_boolean.chores_monthly_change_air_filter
        - input_boolean.chores_monthly_clean_appliances
        - input_boolean.chores_monthly_clean_light_fixtures
        - input_boolean.chores_monthly_wash_bedding
    action: input_boolean.turn_off
mode: single
