alias: Home Assistant Voice - Double Press - Announce Blood Sugar
description: ""
triggers:
  - entity_id: event.home_assistant_voice_0a1e11_button_press
    attribute: event_type
    to: double_press
    trigger: state
conditions: []
actions:
  - target:
      entity_id:
        - assist_satellite.home_assistant_voice_0a1e11_assist_satellite
        - assist_satellite.home_assistant_voice_0a171f_assist_satellite
    data:
      preannounce: true
      message: >
        Your current blood sugar is {{ states('sensor.USERNAME_glucose_value')
        }}.
    action: assist_satellite.announce
mode: single
